---
project:
  type: website

website:
  title: "How to Git with FEWS"
  navbar:
    left:
      - text: "How to Git with FEWS"
        file: index.qmd
    right:
      - icon: github
        href: https://github.com/hkv-consultants/how_to_git_with_fews
        aria-label: GitHub
format:
  html:
    theme: cosmo
    toc: true
